name: Build on Windows
on:
  push
  # FIXME
  # push:
  #   branches:
  #     - main
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2

      - name: Install build toolchain
        run: |
          choco install python --version 3.11.0
          pip install --upgrade pip setuptools build
          pip install pyinstaller pipenv

      - name: Install dependencies
        run: |
          pipenv requirements > requirements.txt
          pip install -r requirements.txt
          rm requirements.txt

      - uses: paulhatch/semantic-version@v4.0.2
        name: Create new version number
        id: version
        with:
          bump_each_commit: true
          tag_prefix: "v"

      - name: git tag
        id: git-tag
        run: |
          git tag ${{ steps.version.outputs.version_tag }}
          git checkout ${{ steps.version.outputs.version_tag }}

      - name: Build package (setuptools)
        run: |
          python -m build

      - name: Build executable (pyinstaller)
        run: |
          pyinstaller -F -n m2fs-${{ steps.version.outputs.version_tag }} -c windows\\m2fs.win64.py

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ steps.version.outputs.version_tag }} dist\\*
