name: Build/release on Windows
on:
  push
  # FIXME
  # push:
  #   branches:
  #     - main
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: paulhatch/semantic-version@v4.0.2
        name: Create new version number
        id: version
        with:
          bump_each_commit: true
          tag_prefix: "v"

      - name: Install build toolchain
        run: |
          choco install python --version 3.11.0
          choco install archive -y
          pip install --upgrade pip setuptools build
          pip install pyinstaller pipenv

      - name: Install dependencies
        run: |
          pipenv requirements > requirements.txt
          pip install -r requirements.txt
          rm requirements.txt

      - name: git tag
        id: git-tag
        run: |
          git tag ${{ steps.version.outputs.version_tag }}
          git checkout ${{ steps.version.outputs.version_tag }}

      - name: Build package (setuptools)
        run: |
          python -m build

      - name: Build and try to run executable (pyinstaller)
        run: |
          set -x

          EXE_NAME=m2fs-${{ steps.version.outputs.version_tag }}-win64
          pyinstaller -p $GITHUB_WORKSPACE -F -n $EXE_NAME -c windows\\m2fs.win64.py

          if ! ./dist/${EXE_NAME} --help; then
            echo "something's not right with the executable distribution"
            exit 1
          fi

          cp examples/generic.py dist/config.py
          archive create -o dist/${EXE_NAME}-standalone.zip README.md dist/${EXE_NAME}.exe dist/config.py
          rm -f dist/*.exe dist/*.py

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git push origin ${{ steps.version.outputs.version_tag }}
          gh release create ${{ steps.version.outputs.version_tag }} dist/*
